### ISSUE TITLE
a gap between conctrol pane and content pane

### ISSUE THREAD

**Issue by qiuchsh** [jcefmaven/jcefbuild#3]
a gap between conctrol pane and content pane, how to remove it
![QQ截图20220615161543](https://user-images.githubusercontent.com/49756310/173778874-b5d89d1d-7774-49e6-9280-69f06b98660b.jpg)
?

**Comment by FriwiDev** [comment]
@qiuchsh https://magpcss.org/ceforum/viewtopic.php?f=17&t=18972&sid=84361f84b1a55cca9d96cd785286b1d8 ;)
