### ISSUE TITLE
GitHub action set-output command deprecated

### ISSUE THREAD

**Issue by FriwiDev** [jcefmaven/jcefbuild#4]
To fix:

- Update action-gh-release with PR: https://github.com/softprops/action-gh-release/pull/266

Will wait on the PR to update

**Comment by alexevanczuk** [comment]
Hi! I saw this referenced in the PR to fix the other deprecation warning, so just wanted to plug you can use the vanilla `gh` CLI client too which I suspect will be very stable. Here's an example:
https://github.com/rubyatscale/use_packwerk/blob/main/.github/workflows/cd.yml

**Comment by FriwiDev** [comment]
@alexevanczuk Thanks for your remark. I changed my code to use the gh client now - it is way better than depending on 3rd party actions :)

**Comment by FriwiDev** [comment]
Changes have been implemented.
