### ISSUE TITLE
demo run error 

### ISSUE THREAD

**Issue by tkggusraqk** [jcefmaven/jcefbuild#5]
os:kylin v10 linux arm64
![jcef-error](https://user-images.githubusercontent.com/5164663/209903559-645d2ab6-f7aa-4c9e-a399-eaa30f2c603c.png)

**Comment by FriwiDev** [comment]
I responded to you on the jcefmaven repo. So I will close this for now.

The newer versions of kylin seem to use more appropriate glibc versions. You may need to upgrade your os.
