### ISSUE TITLE
Use JetBrains/jcef instead

### ISSUE THREAD

**Issue by Osiris-Team** [jcefmaven/jcefbuild#6]
It looks like the [JetBrains fork](https://github.com/JetBrains/jcef) contains a lot more features than the original, for example the ability to access the offscreen rendered image (which I need). I already created a feature request [here](https://bitbucket.org/chromiumembedded/java-cef/issues/432/retrieve-rendered-image-from-cefbrowserosr)
but I doubt that it will be added any time soon if it even gets added.

Would it be possible for you to create a new branch that uses that fork to create the maven artifacts, or include it in the current branch?
I would really appreciate that!

I am trying it on my fork, but without success: https://github.com/Osiris-Team/jetbrains-jcefbuild/actions/workflows/build-all.yml
https://bitbucket.org/Osiris-Team/java-cef/src/master/
I also cannot publish artifacts to maven, so i'd have to somehow make it work via JitPack...

**Comment by FriwiDev** [comment]
@Osiris-Team I sadly can not currently put in the required time to create artifacts from the jetbrains fork of jcef as the builds do not seem completely compatible. If you manage to fix the build on your fork I can gladly provide signatures and deploy them to maven, as long as the license supports this.

**Comment by Osiris-Team** [comment]
@FriwiDev I created my own fork of jcef, that adds the feature I needed, namely accessing the rendered image: https://bitbucket.org/Osiris-Team/java-cef/src/master/
It would be very nice if you could upload it to maven. Its based on the lastest master branch so I think it should work.
I'll add you as admin, so u can also push changes to the repo, and we could use it as our custom branch with a few fixes/enhancements here and there. What do you think?

**Comment by FriwiDev** [comment]
@Osiris-Team I think the most solid approach would be to open a merge request to the jcef master on bitbucket. You can assign magreenblatt as reviewer. It then usually gets merged within some days, as long as it works and adheres to the chromium code style. This way we could prevent unnecessary branching.

**Comment by Osiris-Team** [comment]
@FriwiDev Yeah I tried that but I dont have perms to create a PR
![image](https://user-images.githubusercontent.com/59899645/216815309-f8c6ddf2-2bb6-437e-ba0c-abd6344bf3ca.png)

**Comment by FriwiDev** [comment]
@Osiris-Team Yeah, that is a bit tricky. You need to open the PR in your repo and not in the jcef repo itself. It will then be shown in the jcef repo pull requests. For some reason bitbucket uses a different scheme for this.

**Comment by Osiris-Team** [comment]
Yeah that worked. Created a PR yesterday. Hopefully it gets merged soon, probably not though. In my experience its a matter of months instead of days.

**Comment by FriwiDev** [comment]
@Osiris-Team I've added some comments to your PR.

**Comment by FriwiDev** [comment]
@Osiris-Team Thanks, I reviewed them and added an approval :)
