### ISSUE TITLE
Unable to build mac without signing

### ISSUE THREAD

**Issue by ctadlock** [jcefmaven/jcefbuild#9]
After forking the repro, I commented out the build script to not codesign mac and ran the GitHub action, but its not generating output.

```
Warning: No files were found with the provided path: out/binary_distrib.tar.gz. No artifacts will be uploaded.
```

Forked changes: https://github.com/jcefmaven/jcefbuild/compare/master...GoToTags:jcefbuild:master

Failed job: https://github.com/GoToTags/jcefbuild/actions/runs/4309458675/jobs/7516874195

**Comment by FriwiDev** [comment]
I sadly can not view the output of your build as I can not expand the categories. Can you please append a paste of the raw log here?

**Comment by ctadlock** [comment]
Here is the log..

[log.txt](https://github.com/jcefmaven/jcefbuild/files/10874879/log.txt)

**Comment by FriwiDev** [comment]
The output looks fine. Your issue is probably only that you commented the cd instruction that is also valid for subsequent archiving commands here: https://github.com/jcefmaven/jcefbuild/compare/master...GoToTags:jcefbuild:master#diff-6d00fbc6f9d4551a5e270a0b8a2a9328e7a654b20781717504a1e947ba41a062L73

If you uncomment it, everything should probably be working :)

**Comment by ctadlock** [comment]
That fixed it. thank you.

**Comment by FriwiDev** [comment]
You're welcome :)

**Comment by ctadlock** [comment]
FYI, been working with the Conveyor team to get JCEF working with packaged Conveyor apps. 

https://github.com/hydraulic-software/jcef-conveyor

**Comment by FriwiDev** [comment]
This looks nice. Once you feel you have reached a production-ready state, make sure to give me a nudge so I can mention the packaging option in the jcefmaven readme :)

**Comment by FriwiDev** [comment]
Ah and btw: JCefMaven includes a class to retrieve the current operating system automatically, without matching any character sets manually. You could also use it in your init code:

```java
EnumPlatform platform = EnumPlatform.getCurrentPlatform();
EnumOS os = platform.getOs();
```

**Comment by ctadlock** [comment]
Will do. Conveyor handles all the codesigning and notorization which is why I need to have jcefbuild not do that work.

We will be using this in the GoToTags Desktop App
https://learn.gototags.com/desktop-app/download

Its for an important feature, to have control over the browser when an nfc/qr/rfid tag is scanned, so mutliple windows arent opened:
https://gitlab.com/gototags/public/-/issues/11

**Comment by FriwiDev** [comment]
Is it unsupported under macos to embed components with a different signature? As far as I am aware including structures that are signed by a different vendor should work totally fine, so my signed stuff should theoretically (as long as conveyor is not an issue) work.

It looks like a nice app to integrate a small webbrowser. I think that html5 interfaces are the future in application development anyways :)
